{
 "title": "Bird",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "birdId", "label": "birdId", "query": "$birdId" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(species.name, ' #', '$birdId' :: TEXT) AS title\nFROM bird JOIN species ON species.id = \"speciesId\"\nWHERE bird.id = '$birdId'"
    }
   ]
  },
  {
   "title": "3D Coordinates",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  latitude,\n  longitude,\n  altitude,\n  \"dateTime\"\nFROM\n  gps_track\nWHERE\n  \"birdId\" = '$birdId'\nLIMIT\n  50"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"birdId\" AS \"Bird ID\",\n  \"colonyId\" AS \"Colony ID\",\n  \"speciesId\" AS \"Species\",\n  COUNT(*) AS \"GPS Tracks\"\nFROM\n  gps_track\n  JOIN bird on bird.id = \"birdId\"\nWHERE\n  \"birdId\" = '$birdId'\nGROUP BY\n  \"birdId\",\n  \"colonyId\",\n  \"speciesId\""
    }
   ]
  },
  {
   "title": "GPS Coordinates",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"birdId\" AS \"Bird\",\n  \"speciesId\" AS \"Species\",\n  latitude AS \"Latitude\",\n  longitude AS \"Longitude\"\nFROM\n  gps_track\n  JOIN bird ON bird.id = \"birdId\"\nWHERE\n  \"birdId\" = '$birdId'"
    }
   ]
  },
  { "title": "GPS Tracks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "GPS Tracks Per Year",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  year :: TEXT AS \"Year\",\n  COUNT(*) AS \"GPS Tracks\"\nFROM\n  gps_track\n  JOIN bird ON bird.id = gps_track.\"birdId\"\nWHERE\n  \"birdId\" = '$birdId'\nGROUP BY\n  year\nORDER BY\n  year"
    }
   ]
  },
  {
   "title": "Dives Per Hour Of The Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Dives\",\n  hours.* :: NUMERIC AS \"Hour\"\nFROM\n  generate_series(0, 23) as hours\n  LEFT JOIN (\n    SELECT\n      COUNT(*) AS \"Dives\",\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      ) :: TEXT AS \"Hour\"\n    FROM\n      gps_track\n      JOIN bird ON bird.id = gps_track.\"birdId\"\n    WHERE\n      \"birdId\" = '$birdId'\n      AND \"isDive0m\" IS TRUE\n    GROUP BY\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      )\n  ) as dives ON dives.\"Hour\" :: NUMERIC = hours.*\nORDER BY\n  \"Hour\" ASC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"dateTime\" AS \"Timestamp\",\n  latitude AS \"Latitude\",\n  longitude AS \"Longitude\",\n  altitude AS \"Altitude\",\n  \"maxDepth\" AS \"Max Depth\",\n  \"coverageRatio\" AS \"Coverage Ratio\",\n  \"isDive0m\",\n  \"isDive1m\",\n  \"isDive2m\",\n  \"isDive3m\",\n  \"isDive4m\",\n  \"isDive5m\" ,\n  year AS \"Year\",\n  unix AS \"Unix Time\",\n  \"birdId\" AS \"Bird ID\"\nFROM\n  gps_track\nWHERE\n  \"birdId\" = '$birdId'\nORDER BY \"dateTime\" ASC"
    }
   ]
  }
 ]
}