{
 "title": "Colonies",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  'Colonies' AS title" }
   ]
  },
  {
   "title": "Centroid of Coordinates",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"colonyId\" AS \"Colony\",\n  \"speciesId\" AS \"Species\",\n  AVG(lat) * (180 / PI()) AS \"Latitude\",\n  AVG(lon) * (180 / PI()) AS \"Longitude\"\nFROM\n  (\n    SELECT\n      \"colonyId\",\n      \"speciesId\",\n      ATAN2(\n        6371000 * SIN(latitude * (PI() / 180)),\n        sqrt(\n          (\n            AVG(\n              6371000 * COS(latitude * (PI() / 180)) * COS(longitude * (PI() / 180))\n            ) * AVG(\n              6371000 * COS(latitude * (PI() / 180)) * COS(longitude * (PI() / 180))\n            )\n          ) + (\n            AVG(\n              6371000 * COS(latitude * (PI() / 180)) * SIN(longitude * (PI() / 180))\n            ) * AVG(\n              6371000 * COS(latitude * (PI() / 180)) * SIN(longitude * (PI() / 180))\n            )\n          )\n        )\n      ) AS lat,\n      ATAN2(\n        AVG(\n          6371000 * COS(latitude * (PI() / 180)) * SIN(longitude * (PI() / 180))\n        ),\n        AVG(\n          6371000 * COS(latitude * (PI() / 180)) * COS(longitude * (PI() / 180))\n        )\n      ) AS lon\n    FROM\n      gps_track\n      JOIN bird ON bird.id = \"birdId\"\n    WHERE\n      gps_track.\"isDive0m\" IS FALSE\n      AND gps_track.\"isDive1m\" IS FALSE\n      AND gps_track.\"isDive2m\" IS FALSE\n      AND gps_track.\"isDive3m\" IS FALSE\n      AND gps_track.\"isDive4m\" IS FALSE\n      AND gps_track.\"isDive5m\" IS FALSE\n    GROUP BY\n      \"colonyId\",\n      \"speciesId\",\n      latitude,\n      longitude\n  ) AS AVG\nGROUP BY\n  \"colonyId\",\n  \"speciesId\""
    }
   ]
  },
  {
   "title": "Colonies",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"colonyId\" AS \"Colony ID\",\n  \"species\" AS \"Species\",\n  \"birds\" AS \"Birds\",\n  \"gpsTracks\" AS \"GPS Tracks\"\nFROM\n  colony_summary\nORDER BY\n  \"colonyId\""
    }
   ]
  },
  {
   "title": "Birds Per Specie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"speciesId\"::TEXT AS \"Species ID\",\n  COUNT(*) AS \"Birds\"\nFROM bird\nGROUP BY\n  \"speciesId\"\nORDER BY \"Birds\" DESC"
    }
   ]
  },
  {
   "title": "Birds Per Colony",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"colonyId\"::TEXT AS \"Colony\",\n  COUNT(*) AS \"Birds\"\nFROM bird\nGROUP BY\n  \"colonyId\"\nORDER BY \"Birds\" DESC"
    }
   ]
  },
  {
   "title": "Birds Per Year",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  year :: TEXT AS \"Year\",\n  COUNT(DISTINCT \"birdId\") AS \"Birds\"\nFROM\n  gps_track\nGROUP BY\n  year\nORDER BY\n  year"
    }
   ]
  },
  { "title": "GPS Tracks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GPS Tracks Per Species",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"speciesId\" AS \"Species\",\n  COUNT(*) AS \"GPS Tracks\"\nFROM\n  gps_track\n  JOIN bird ON bird.id = gps_track.\"birdId\"\nGROUP BY\n  \"speciesId\"\nORDER BY\n  \"GPS Tracks\" DESC"
    }
   ]
  },
  {
   "title": "GPS Tracks Per Colony",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"colonyId\" :: TEXT AS \"Colony\",\n  COUNT(*) AS \"GPS Tracks\"\nFROM\n  gps_track\n  JOIN bird ON bird.id = gps_track.\"birdId\"\nGROUP BY\n  \"colonyId\"\nORDER BY\n  \"colonyId\""
    }
   ]
  },
  {
   "title": "GPS Tracks Per Year",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  year :: TEXT AS \"Year\",\n  COUNT(*) AS \"GPS Tracks\"\nFROM\n  gps_track\n  JOIN bird ON bird.id = gps_track.\"birdId\"\nGROUP BY\n  year\nORDER BY\n  year"
    }
   ]
  },
  {
   "title": "tRAZO - Dives Per Hour Of The Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Dives\",\n  hours.* :: NUMERIC AS \"Hour\"\nFROM\n  generate_series(0, 23) as hours\n  LEFT JOIN (\n    SELECT\n      COUNT(*) AS \"Dives\",\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      ) :: TEXT AS \"Hour\"\n    FROM\n      gps_track\n      JOIN bird ON bird.id = gps_track.\"birdId\"\n    WHERE\n      \"isDive0m\" IS TRUE\n      AND \"speciesId\" = 'tRAZO'\n    GROUP BY\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      )\n  ) as dives ON dives.\"Hour\" :: NUMERIC = hours.*\nORDER BY\n  \"Hour\" ASC"
    }
   ]
  },
  {
   "title": "tCOGU - Dives Per Hour Of The Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Dives\",\n  hours.* :: NUMERIC AS \"Hour\"\nFROM\n  generate_series(0, 23) as hours\n  LEFT JOIN (\n    SELECT\n      COUNT(*) AS \"Dives\",\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      ) :: TEXT AS \"Hour\"\n    FROM\n      gps_track\n      JOIN bird ON bird.id = gps_track.\"birdId\"\n    WHERE\n      \"isDive0m\" IS TRUE\n      AND \"speciesId\" = 'tCOGU'\n    GROUP BY\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      )\n  ) as dives ON dives.\"Hour\" :: NUMERIC = hours.*\nORDER BY\n  \"Hour\" ASC"
    }
   ]
  },
  {
   "title": "tEUSH- Dives Per Hour Of The Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Dives\",\n  hours.* :: NUMERIC AS \"Hour\"\nFROM\n  generate_series(0, 23) as hours\n  LEFT JOIN (\n    SELECT\n      COUNT(*) AS \"Dives\",\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      ) :: TEXT AS \"Hour\"\n    FROM\n      gps_track\n      JOIN bird ON bird.id = gps_track.\"birdId\"\n    WHERE\n      \"isDive0m\" IS TRUE\n      AND \"speciesId\" = 'tEUSH'\n    GROUP BY\n      EXTRACT(\n        HOUR\n        FROM\n          \"dateTime\" AT TIME ZONE 'UTC'\n      )\n  ) as dives ON dives.\"Hour\" :: NUMERIC = hours.*\nORDER BY\n  \"Hour\" ASC"
    }
   ]
  }
 ]
}